# Email configration
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: <Gmail_ID>
    password: <App Password From gmail>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
                        

